const DEFAULT_STORAGE_QUOTA = 15 * 1024 * 1024 * 1024; // 15 GB
const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100 MB
const TRASH_RETENTION_DAYS = 30;

const CATEGORIES = {
  IMAGE: "image",
  VIDEO: "video",
  AUDIO: "audio",
  PDF: "pdf",
  DOCUMENT: "document",
  ARCHIVE: "archive",
  CODE: "code",
  OTHER: "other",
};

const ACTIVITY_ACTIONS = {
  FILE_UPLOAD: "FILE_UPLOAD",
  FILE_DOWNLOAD: "FILE_DOWNLOAD",
  FILE_RENAME: "FILE_RENAME",
  FILE_MOVE: "FILE_MOVE",
  FILE_TRASH: "FILE_TRASH",
  FILE_RESTORE: "FILE_RESTORE",
  FILE_DELETE_PERMANENT: "FILE_DELETE_PERMANENT",
  FOLDER_CREATE: "FOLDER_CREATE",
  FOLDER_RENAME: "FOLDER_RENAME",
  FOLDER_MOVE: "FOLDER_MOVE",
  FOLDER_TRASH: "FOLDER_TRASH",
  FOLDER_RESTORE: "FOLDER_RESTORE",
  FOLDER_DELETE_PERMANENT: "FOLDER_DELETE_PERMANENT",
  FOLDER_DOWNLOAD: "FOLDER_DOWNLOAD",
  SHARE_CREATED: "SHARE_CREATED",
  SHARE_REVOKED: "SHARE_REVOKED",
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
};

module.exports = {
  DEFAULT_STORAGE_QUOTA,
  MAX_FILE_SIZE,
  TRASH_RETENTION_DAYS,
  CATEGORIES,
  ACTIVITY_ACTIONS,
};
